@host = http://localhost:8080

@username = andrewMarshall
@email = andrew@the_email.com
@password = Andrew1234
@mascotId = 1
@bio = I got nothing to say

@post_id = 1

### Create User
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "mascotId": {{mascotId}},
    "bio": "{{bio}}"
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("user_id", response.body.id);
    client.global.set("userAccessToken", response.body.accessToken);
%}

### Create Comment
POST {{host}}/api/posts/{{post_id}}/comments
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "commentBody": "Literally hilarious",
    "parentId": null
}

> {%
    client.global.set("comment_id", response.body.commentId)
 %}

### Update Comment 1
PATCH {{host}}/api/comments/{{comment_id}}
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "commentBody": "Literally stupid funny"
}

### Update Comment 2
PATCH {{host}}/api/comments/{{comment_id}}
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "commentBody": "Literally hilarious"
}

### Delete Comment
DELETE {{host}}/api/comments/{{comment_id}}

### Get Post Comments
GET {{host}}/api/posts/{{post_id}}/comments

### Delete Self (Admin)
DELETE {{host}}/api/user/me
Authorization: Bearer {{adminAccessToken}}
