@host = http://localhost:8080
@mascot_id = 1
@out_of_range = 1000
@soft_deleted_404= 8

### Get Mascot
GET {{host}}/api/mascots/{{mascot_id}}

### Get Mascot out of range error (expect 404)
GET {{host}}/api/mascots/{{out_of_range}}

### Get Mascot that was soft deleted (expect 404)
GET {{host}}/api/mascots/{{soft_deleted_404}}
