@host = http://localhost:8080
@post_id = 1
@out_of_range = 1000

### Get Post
GET {{host}}/api/v1/posts/{{post_id}}

### Get Post out of range error (expect 404)
GET {{host}}/api/v1/posts/{{out_of_range}}
