@host = http://localhost:8080
@user_id = 1
@out_of_range = 1000

### Get User
GET {{host}}/api/v1/users/{{user_id}}/posts

### Get User out of range error (expect 404)
GET {{host}}/api/v1/users/{{out_of_range}}/posts
