@host = http://localhost:8080

@username = andrewMarshall
@email = andrew@the_email.com
@password = Andrew1234
@mascotId = 1
@bio = I got nothing to say

@newUsername = andrewMarshall
@newEmail = andrew@the_email.com
@newPassword = Hello1234
@newMascotId = 1
@newBio = I got nothing to say

### Create User
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "mascotId": {{mascotId}},
    "bio": "{{bio}}"
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("userAccessToken", response.body.accessToken);
%}

### Get Self
GET {{host}}/api/users/me

### Create Post 1
POST {{host}}/api/posts
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "title": "How to Bake Cookies",
    "body": "You gotta get the pan, you gotta get the wax paper, and the cookie dough",
    "threadId": {{thread_id}}
}

### Create Post 2
POST {{host}}/api/posts
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "title": "How to Bake Cookies",
    "body": "You gotta get the pan, you gotta get the wax paper, and the cookie dough",
    "threadId": {{thread_id}}
}

### Get Self Posts
GET {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}

### Update Self 1 param
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "username": "{{newUsername}}"
}

### Update Self 3 param
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "email": "{{newEmail}}",
    "mascotId": {{newMascotId}},
    "bio": "{{newBio}}"
}

### Update Self Password
PATCH {{host}}/api/users/me/password
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "oldPassword": "{{password}}",
    "newPassword": "{{newPassword}}"
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{newPassword}}"
}

### Update Self Password Back to Original
PATCH {{host}}/api/users/me/password
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "oldPassword": "{{newPassword}}",
    "newPassword": "{{password}}"
}

### Delete Self
DELETE {{host}}/api/users/me
