@host = http://localhost:8080

@username = ThePigMonsterMan
@password = ThePigMonster1234Man
@email = pig_monster_man@user.com

@newPassword = ThePigMo_mannster3026_1234

### Create Admin
POST {{host}}/api/auth/admins
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "mascotId": 1,
    "bio": "I got nothing to say"
}

### Login Admin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("adminAccessToken", response.body.accessToken.token);
%}

### Update Admin 1
PATCH {{host}}/api/users/me/password
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "oldPassword": "{{password}}",
    "newPassword": "{{newPassword}}"
}

### Login Admin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{newPassword}}"
}

> {%
    client.global.set("adminAccessToken", response.body.accessToken.token);
%}

### Delete Admin
DELETE {{host}}/api/users/me
Authorization: Bearer {{adminAccessToken}}