@host = http://localhost:8080

@thread_id = 2
@user_post_id = 1

@username = andrewMarshall
@email = andrew@the_email.com
@password = Andrew1234
@mascotId = 1
@bio = I got nothing to say

@adminUsername = andrew_the_admin
@adminEmail = andrew_the_admin@the_email.com
@adminPassword = Andrew1234
@adminMascotId = 1
@adminBio = I got nothing to say

### Create User
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "mascotId": {{mascotId}},
    "bio": "{{bio}}"
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("user_id", response.body.id);
    client.global.set("accessToken", response.body.accessToken);
%}

### Create Post
POST {{host}}/api/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Dinosaurs",
    "body": "You gotta use intelliJ and just type and hope for the best tbh",
    "threadId": {{thread_id}}
}

> {%
    client.global.set("post_id", response.body.postId);
    console.log(response.body.postId)
 %}

### Update Post 1 param
POST {{host}}/api/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "How to test with Http files boo yah",
    "body": "You gotta use The terminal and just type and hope for the best tbh",
    "threadId": 1
}

### Update Post 2 param
POST {{host}}/api/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "How to test with Http files",
    "body": "You gotta use intelliJ and just type and hope for the best tbh",
    "threadId": {{thread_id}}
}

### Get Post
GET {{host}}/api/posts/{{post_id}}

### Delete Post
DELETE {{host}}/api/posts/{{post_id}}
Authorization: Bearer {{accessToken}}

### Get Thread Posts
GET {{host}}/api/threads/{{thread_id}}/posts

### Get User Posts
GET {{host}}/api/users/{{user_id}}/posts

### Get User Posts
GET {{host}}/api/users/{{user_post_id}}/posts

### Delete Self
DELETE {{host}}/api/user/me
Authorization: Bearer {{accessToken}}
