@host = http://localhost:8080

@username = andrewMarshall
@email = andrew@the_email.com
@password = Andrew1234
@mascotId = 1
@bio = I got nothing to say

@adminUsername = andrew_the_admin
@adminEmail = andrew_the_admin@the_email.com
@adminPassword = Andrew1234
@adminMascotId = 1
@adminBio = I got nothing to say

### Create User
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "mascotId": {{mascotId}},
    "bio": "{{bio}}"
}

### Create Admin
POST {{host}}/api/auth/admins
Content-Type: application/json

{
    "username": "{{adminUsername}}",
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}",
    "mascotId": {{adminMascotId}},
    "bio": "{{adminBio}}"
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("user_id", response.body.id);
    client.global.set("userAccessToken", response.body.accessToken);
 %}

### Login Admin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {%
    client.global.set("admin_id", response.body.id);
    client.global.set("adminAccessToken", response.body.accessToken);
%}

### Get User
GET {{host}}/api/users/{{user_id}}

### Get Admin
GET {{host}}/api/users/{{admin_id}}

### Update Self 1 param (User)
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "email": "andrew@andrew.com"
}

### Update Self 2 params (User)
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "mascotId": 2,
  "bio": "Whats up people"
}

### Update Self back to Original 3 params (User)
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "email": "andrew@marshall.com",
    "mascotId": 1,
    "bio": "I got nothing to say"
}

### Update Self (Admin)
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "email": "andrew@the_admin.com",
  "mascotId": 3,
  "bio": "I am the admin guys"
}

### Update Self back to Original (Admin)
PATCH {{host}}/api/users/me
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
    "email": "andrew@admin.com",
    "mascotId": 1,
    "bio": "I got nothing to say"
}

### Delete User
DELETE {{host}}/api/users/{{user_id}}
Authorization: Bearer {{adminAccessToken}}

### Delete Self (Admin)
DELETE {{host}}/api/user/me
Authorization: Bearer {{adminAccessToken}}
